import streamlit as st
from groq import Groq
from google import genai
from google.genai import types
from io import BytesIO
from PIL import Image

# --- 1. AUTH & SETUP ---
# Ensure these keys are in your Streamlit Secrets
groq_key = st.secrets.get("GROQ_API_KEY")
google_key = st.secrets.get("GOOGLE_API_KEY")

client_groq = Groq(api_key=groq_key)
client_google = genai.Client(api_key=google_key)

st.set_page_config(page_title="Run&Drive AI", layout="wide")

# --- 2. THE DESIGN (CSS) ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@900&display=swap');
    .stApp { background-color: #ffffff; }
    #MainMenu, footer, header, .stDeployButton, div[data-testid="stToolbar"] {visibility: hidden; display: none;}

    .main-title {
        font-family: 'Montserrat', sans-serif;
        font-size: clamp(3rem, 10vw, 6rem);
        color: #000000;
        text-align: center;
        margin-bottom: 0;
    }

    .img-container {
        position: relative;
        width: 100%;
        border-radius: 20px;
        overflow: hidden;
        border: 4px solid #32cd32;
        margin-top: 20px;
    }
    .img-tag {
        position: absolute;
        top: 15px;
        left: 15px;
        background: rgba(0,0,0,0.8);
        color: #32cd32;
        padding: 5px 15px;
        border-radius: 5px;
        font-size: 0.7rem;
        font-weight: bold;
        z-index: 99;
    }
    .stat-card {
        background: white;
        padding: 25px;
        border-radius: 15px;
        border-bottom: 5px solid #32cd32;
        text-align: center;
        box-shadow: 0 10px 30px rgba(0,0,0,0.05);
        margin-top: 20px;
    }
    </style>
    """, unsafe_allow_html=True)

# --- 3. UI ---
st.markdown('<h1 class="main-title">Run&Drive</h1>', unsafe_allow_html=True)
st.markdown('<p style="text-align:center; color:#32cd32; font-weight:800; letter-spacing:3px;">INSTITUTIONAL AI ANALYTICS</p>', unsafe_allow_html=True)

with st.columns([1,2,1])[1]:
    with st.form("main_form"):
        brand = st.text_input("Brand", placeholder="e.g. Mercedes")
        model = st.text_input("Model", placeholder="e.g. G-Wagon")
        year = st.number_input("Year", value=2024)
        submit = st.form_submit_button("RUN ANALYSIS")

# --- 4. EXECUTION ---
if submit and brand and model:
    with st.spinner("AI Engine Engaging..."):
        try:
            # A. DATA ANALYSIS (Groq)
            text_prompt = f"Analyze {year} {brand} {model}. Format: PRICE: [val] | TREND: [status]"
            text_res = client_groq.chat.completions.create(
                messages=[{"role":"user","content":text_prompt}], 
                model="llama-3.3-70b-versatile"
            ).choices[0].message.content
            
            # B. IMAGE GENERATION (Gemini 3.1)
            img_prompt = f"A professional high-end studio car photograph of a {year} {brand} {model}, cinematic lighting, 4k, clean white background."
            img_res = client_google.models.generate_content(
                model="gemini-3.1-flash-image-preview",
                contents=[img_prompt],
                config=types.GenerateContentConfig(response_modalities=["IMAGE"])
            )
            
            # --- THE 2026 BINARY FIX ---
            found_image = False
            for part in img_res.candidates[0].content.parts:
                if part.inline_data:
                    # In the new SDK, we read the data directly as bytes
                    img_bytes = part.inline_data.data
                    final_image = Image.open(BytesIO(img_bytes))
                    
                    st.markdown('<div class="img-container"><div class="img-tag">PICTURE GENERATED BY RUN&DRIVE AI</div></div>', unsafe_allow_html=True)
                    st.image(final_image, use_container_width=True)
                    found_image = True

            if not found_image:
                st.warning("Car visual skipped by AI safety filters. Displaying data only.")

            # C. THE STATS
            price = text_res.split("PRICE:")[1].split("|")[0].strip()
            trend = text_res.split("TREND:")[1].strip()
            
            sc1, sc2 = st.columns(2)
            sc1.markdown(f'<div class="stat-card"><small>ESTIMATED PRICE</small><h1 style="color:#32cd32;">{price}</h1></div>', unsafe_allow_html=True)
            sc2.markdown(f'<div class="stat-card"><small>MARKET TREND</small><h1>{trend}</h1></div>', unsafe_allow_html=True)

        except Exception as e:
            st.error(f"Error: {e}")
